### PR TITLE
Allowing the user to select a specific property of the serviceCatalog to resolve storageURL

### PR DESCRIPTION
**Pull request by kplaube**
At Globo.com we use Openstack/Swift to keep our static files. I don't know why, but here, we interact with our resource through adminURL instead of publicURL.

So, I tried to improve this part of the code, allowing me use this lib to upload our files (using Node.JS) to our Swift instances.

### CODE REVIEW

**Comment by almirfilho** [comment]
Hi @jasonmadigan, any updates on that?
I think this feature is very useful. I'm needing this too =)

**Comment by rfloriano** [comment]
Bump!

I really need this feature too!

**Comment by rfloriano** [comment]
Thanks @jasonmadigan!! :D

**Comment by kplaube** [comment]
Thanks a lot, @jasonmadigan!

**Pull request merged**
